DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS places CASCADE;
DROP TABLE IF EXISTS sharelists CASCADE;
DROP TABLE IF EXISTS lists CASCADE;

CREATE TABLE users(
  id SERIAL PRIMARY KEY,
  email VARCHAR NOT NULL UNIQUE,
  password_digest VARCHAR NOT NULL
);

CREATE TABLE lists(
  list_id SERIAL PRIMARY KEY,
  list_name VARCHAR NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL
);

CREATE TABLE places(
  place_id SERIAL PRIMARY KEY,
  google_icon VARCHAR,
  google_place_id VARCHAR NOT NULL,
  name VARCHAR NOT NULL,
  rating DECIMAL,
  checked BOOLEAN DEFAULT FALSE,
  lat DECIMAL NOT NULL,
  lng DECIMAL NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  list_u_id INTEGER REFERENCES lists(list_id) ON DELETE CASCADE NOT NULL
);

CREATE TABLE sharelists(
  share_id SERIAL PRIMARY KEY,
  sharedlist_name VARCHAR NOT NULL,
  list_u_id INTEGER REFERENCES lists(list_id) ON DELETE CASCADE NOT NULL
);
